version: '3'
volumes:
  persitent-storage:
services:
  influxdb:
    image: influxdb:1.7-alpine
    restart: always
  grafana:
    image: grafana/grafana:5.4.3
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - 'persitent-storage:/var/lib/grafana'
  sensor:
    build: .
    restart: always
    environment:
      - INFLUX_HOST=influxdb
    depends_on:
      - influxdb
      - grafana
