version: '3'
volumes:
  persitent-storage:
services:
  influxdb:
    image: influxdb:1.7
    restart: always
  grafana:
    image: grafana/grafana:5.4.3
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - 'persitent-storage:/var/lib/grafana'
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
  sensor:
    build: ./sensors/cpu_load
    restart: always
    environment:
      - INFLUX_HOST=influxdb
    depends_on:
      - influxdb
      - grafana
