version: '3'
volumes:
  persitent-storage:
services:
  influxdb:
    image: influxdb:1.7
    volumes:
      - 'persitent-storage:/var/lib/influxdb'
  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - "3000:3000"
    volumes:
      - 'persitent-storage:/var/lib/grafana'
