version: '3'
services:
  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
