apiVersion: 1
datasources:
  - name: Influxdb
    type: influxdb
    access: proxy
    database: multi-sense
    user: root
    password: root
    url: http://influxdb:8086
    isDefault: true
    editable: true
    
